# Generated by Django 4.2.2 on 2023-07-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionesPersonal', '0002_accionpersonal_estado_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionpersonal',
            name='estado_accion',
            field=models.CharField(blank=True, choices=[('VIGENTE', 'VIGENTE'), ('LEGALIZADO', 'LEGALIZADO'), ('ANULADO', 'ANULADO')], default='VIGENTE', max_length=255, null=True, verbose_name='Estado acción de personal'),
        ),
        migrations.AlterField(
            model_name='historicalaccionpersonal',
            name='estado_accion',
            field=models.CharField(blank=True, choices=[('VIGENTE', 'VIGENTE'), ('LEGALIZADO', 'LEGALIZADO'), ('ANULADO', 'ANULADO')], default='VIGENTE', max_length=255, null=True, verbose_name='Estado acción de personal'),
        ),
    ]
