# Generated by Django 4.2.2 on 2023-07-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionesPersonal', '0004_alter_accionpersonal_tipo_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionpersonal',
            name='doc_base',
            field=models.CharField(blank=True, choices=[('VIGENTE', 'VIGENTE'), ('LEGALIZADO', 'LEGALIZADO'), ('ANULADO', 'ANULADO')], max_length=255, null=True, verbose_name='Documento base'),
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='fecha_doc',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha documento base'),
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='fecha_rigue',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha rigue'),
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='num_doc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número documento base'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='doc_base',
            field=models.CharField(blank=True, choices=[('VIGENTE', 'VIGENTE'), ('LEGALIZADO', 'LEGALIZADO'), ('ANULADO', 'ANULADO')], max_length=255, null=True, verbose_name='Documento base'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='fecha_doc',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha documento base'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='fecha_rigue',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha rigue'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='num_doc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número documento base'),
        ),
        migrations.AlterField(
            model_name='accionpersonal',
            name='explicacion',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Explicacion'),
        ),
        migrations.AlterField(
            model_name='historicalaccionpersonal',
            name='explicacion',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Explicacion'),
        ),
    ]
