# Generated by Django 4.2.2 on 2023-07-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accionesPersonal', '0005_accionpersonal_doc_base_accionpersonal_fecha_doc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accionpersonal',
            old_name='fecha',
            new_name='fecha_accion',
        ),
        migrations.RenameField(
            model_name='historicalaccionpersonal',
            old_name='fecha',
            new_name='fecha_accion',
        ),
    ]
