# Generated by Django 4.2.2 on 2023-07-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionesPersonal', '0006_rename_fecha_accionpersonal_fecha_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionpersonal',
            name='doc_base',
            field=models.CharField(blank=True, choices=[('DECRETO', 'DECRETO'), ('ACUERDO', 'ACUERDO'), ('RESOLUCION', 'RESOLUCION')], max_length=255, null=True, verbose_name='Documento base'),
        ),
        migrations.AlterField(
            model_name='historicalaccionpersonal',
            name='doc_base',
            field=models.CharField(blank=True, choices=[('DECRETO', 'DECRETO'), ('ACUERDO', 'ACUERDO'), ('RESOLUCION', 'RESOLUCION')], max_length=255, null=True, verbose_name='Documento base'),
        ),
    ]
