# Generated by Django 4.2.2 on 2023-07-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionesPersonal', '0008_accionpersonal_partida_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionpersonal',
            name='estructura_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='estructura_actual'),
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='estructura_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='estructura_propuesta'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='estructura_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='estructura_actual'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='estructura_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='estructura_propuesta'),
        ),
    ]
