# Generated by Django 4.2.2 on 2023-09-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accionesPersonal', '0010_archivoacciones_historicalarchivoacciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accionpersonal',
            options={'ordering': ['-contador'], 'verbose_name': 'Acción de personal', 'verbose_name_plural': 'Acciones de personal'},
        ),
    ]
