# Generated by Django 4.2.2 on 2023-10-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionesPersonal', '0011_alter_accionpersonal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionpersonal',
            name='otro_tipo',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Otro tipo de acción'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='otro_tipo',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Otro tipo de acción'),
        ),
    ]
