# Generated by Django 4.2.2 on 2023-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionesPersonal', '0012_accionpersonal_otro_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionpersonal',
            name='partida_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='partida_propuesta'),
        ),
        migrations.AlterField(
            model_name='accionpersonal',
            name='proceso_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='proceso_propuesta'),
        ),
        migrations.AlterField(
            model_name='accionpersonal',
            name='puesto_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='puesto_propuesta'),
        ),
        migrations.AlterField(
            model_name='accionpersonal',
            name='rmu_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='rmu_propuesta'),
        ),
        migrations.AlterField(
            model_name='accionpersonal',
            name='subproceso_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subproceso_propuesta'),
        ),
        migrations.AlterField(
            model_name='historicalaccionpersonal',
            name='partida_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='partida_propuesta'),
        ),
        migrations.AlterField(
            model_name='historicalaccionpersonal',
            name='proceso_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='proceso_propuesta'),
        ),
        migrations.AlterField(
            model_name='historicalaccionpersonal',
            name='puesto_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='puesto_propuesta'),
        ),
        migrations.AlterField(
            model_name='historicalaccionpersonal',
            name='rmu_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='rmu_propuesta'),
        ),
        migrations.AlterField(
            model_name='historicalaccionpersonal',
            name='subproceso_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subproceso_propuesta'),
        ),
    ]
