# Generated by Django 4.2.7 on 2024-11-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionesPersonal', '0014_alter_accionpersonal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionpersonal',
            name='declaracion_jurada',
            field=models.BooleanField(default=True, verbose_name='Delcaracion jurada'),
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='detalle_tipo_accion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalle tipo accion'),
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='fecha_rigue_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha rigue hasta'),
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='grupo_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grupo_actual'),
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='grupo_actual_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grupo_actual_propuesta'),
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='grupo_ocupacional_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grupo_ocupacional_actual'),
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='grupo_ocupacional_actual_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grupo_ocupacional_actual_propuesta'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='declaracion_jurada',
            field=models.BooleanField(default=True, verbose_name='Delcaracion jurada'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='detalle_tipo_accion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalle tipo accion'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='fecha_rigue_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha rigue hasta'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='grupo_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grupo_actual'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='grupo_actual_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grupo_actual_propuesta'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='grupo_ocupacional_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grupo_ocupacional_actual'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='grupo_ocupacional_actual_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grupo_ocupacional_actual_propuesta'),
        ),
        migrations.AlterField(
            model_name='accionpersonal',
            name='tipo_accion',
            field=models.CharField(blank=True, choices=[('INGRESO', 'INGRESO'), ('REINGRESO', 'REINGRESO'), ('RESTITUCION', 'RESTITUCION'), ('REINTEGRO', 'REINTEGRO'), ('ASCENSO', 'ASCENSO'), ('TRASLADO', 'TRASLADO'), ('TRASPASO', 'TRASPASO'), ('CAMBIO ADMINISTRATIVO', 'CAMBIO ADMINISTRATIVO'), ('INTERCAMBIO VOLUNTARIO', 'INTERCAMBIO VOLUNTARIO'), ('LICENCIA', 'LICENCIA'), ('COMISION DE SERVICIOS', 'COMISION DE SERVICIOS'), ('SANCIONES', 'SANCIONES'), ('INCREMENTO RMU', 'INCREMENTO RMU'), ('SUBROGACION', 'SUBROGACION'), ('ENCARGO', 'ENCARGO'), ('CESACION DE FUNCIONES', 'CESACION DE FUNCIONES'), ('DESTITUCION', 'DESTITUCION'), ('VACACIONES', 'VACACIONES'), ('REVISION CLASI. PUESTO', 'REVISION CLASI. PUESTO'), ('OTRO', 'OTRO')], max_length=255, null=True, verbose_name='Tipo acción de personal'),
        ),
        migrations.AlterField(
            model_name='historicalaccionpersonal',
            name='tipo_accion',
            field=models.CharField(blank=True, choices=[('INGRESO', 'INGRESO'), ('REINGRESO', 'REINGRESO'), ('RESTITUCION', 'RESTITUCION'), ('REINTEGRO', 'REINTEGRO'), ('ASCENSO', 'ASCENSO'), ('TRASLADO', 'TRASLADO'), ('TRASPASO', 'TRASPASO'), ('CAMBIO ADMINISTRATIVO', 'CAMBIO ADMINISTRATIVO'), ('INTERCAMBIO VOLUNTARIO', 'INTERCAMBIO VOLUNTARIO'), ('LICENCIA', 'LICENCIA'), ('COMISION DE SERVICIOS', 'COMISION DE SERVICIOS'), ('SANCIONES', 'SANCIONES'), ('INCREMENTO RMU', 'INCREMENTO RMU'), ('SUBROGACION', 'SUBROGACION'), ('ENCARGO', 'ENCARGO'), ('CESACION DE FUNCIONES', 'CESACION DE FUNCIONES'), ('DESTITUCION', 'DESTITUCION'), ('VACACIONES', 'VACACIONES'), ('REVISION CLASI. PUESTO', 'REVISION CLASI. PUESTO'), ('OTRO', 'OTRO')], max_length=255, null=True, verbose_name='Tipo acción de personal'),
        ),
    ]
