# Generated by Django 4.2.7 on 2024-11-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionesPersonal', '0015_accionpersonal_declaracion_jurada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accionpersonal',
            name='grupo_actual',
        ),
        migrations.RemoveField(
            model_name='accionpersonal',
            name='grupo_actual_propuesta',
        ),
        migrations.RemoveField(
            model_name='historicalaccionpersonal',
            name='grupo_actual',
        ),
        migrations.RemoveField(
            model_name='historicalaccionpersonal',
            name='grupo_actual_propuesta',
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='grado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grado'),
        ),
        migrations.AddField(
            model_name='accionpersonal',
            name='grado_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grado_propuesta'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='grado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grado'),
        ),
        migrations.AddField(
            model_name='historicalaccionpersonal',
            name='grado_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='grado_propuesta'),
        ),
    ]
