# Generated by Django 4.2.7 on 2024-12-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accionesPersonal', '0021_remove_accionpersonal_grupo_ocupacional_actual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accionpersonal',
            old_name='escala_ocupacional_actual_propuesta',
            new_name='escala_ocupacional_propuesta',
        ),
        migrations.RenameField(
            model_name='historicalaccionpersonal',
            old_name='escala_ocupacional_actual_propuesta',
            new_name='escala_ocupacional_propuesta',
        ),
    ]
