# Generated by Django 4.2.2 on 2023-09-27 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0007_datospersonalestrabajadores_alter_trabajador_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoPermiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de eliminación')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo del permiso')),
            ],
            options={
                'verbose_name': ('motivo de permiso',),
                'verbose_name_plural': 'motivos del permiso',
                'db_table': 'Motivo_Permiso',
                'ordering': ['motivo'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de eliminación')),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Salida')),
                ('fecha_hora_llegada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de LLegada')),
                ('detalle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalle')),
                ('min_acumulados', models.IntegerField(blank=True, null=True, verbose_name='Minutos del permiso')),
                ('horas_almuerzo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Horas de almuerzo')),
                ('otra_hora', models.TimeField(blank=True, null=True, verbose_name='Otra hora de almuerzo')),
                ('certificado_medico', models.BooleanField(default=False, verbose_name='Certificado médico')),
                ('id_motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permisos.motivopermiso', verbose_name='Motivo')),
                ('id_trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
                'db_table': 'Permisos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPermiso',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Salida')),
                ('fecha_hora_llegada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de LLegada')),
                ('detalle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalle')),
                ('min_acumulados', models.IntegerField(blank=True, null=True, verbose_name='Minutos del permiso')),
                ('horas_almuerzo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Horas de almuerzo')),
                ('otra_hora', models.TimeField(blank=True, null=True, verbose_name='Otra hora de almuerzo')),
                ('certificado_medico', models.BooleanField(default=False, verbose_name='Certificado médico')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_motivo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permisos.motivopermiso', verbose_name='Motivo')),
                ('id_trabajador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trabajadores.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'historical permiso',
                'verbose_name_plural': 'historical permisos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMotivoPermiso',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo del permiso')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical ('motivo de permiso',)",
                'verbose_name_plural': 'historical motivos del permiso',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
