# Generated by Django 4.2.2 on 2023-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpermiso',
            name='detalle',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='detalle',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Detalle'),
        ),
    ]
