# Generated by Django 4.2.2 on 2023-07-03 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_historicaltrabajador_dias_vacaciones_and_more'),
        ('permisos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermiso',
            name='id_trabajador',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trabajadores.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='id_trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador', verbose_name='Trabajador'),
        ),
    ]
