# Generated by Django 4.2.2 on 2023-07-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0003_historicalpermiso_id_trabajador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpermiso',
            name='fecha_hora_estimada',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='fecha_hora_estimada',
        ),
    ]
