# Generated by Django 4.2.2 on 2023-07-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0002_rename_cronograma_vacaciones_cronogramavacaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramavacaciones',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha solicitud'),
        ),
        migrations.AddField(
            model_name='historicalcronogramavacaciones',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha solicitud'),
        ),
        migrations.AlterField(
            model_name='cronogramavacaciones',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha hasta'),
        ),
        migrations.AlterField(
            model_name='cronogramavacaciones',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha desde'),
        ),
        migrations.AlterField(
            model_name='historicalcronogramavacaciones',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha hasta'),
        ),
        migrations.AlterField(
            model_name='historicalcronogramavacaciones',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha desde'),
        ),
    ]
