# Generated by Django 4.2.2 on 2023-07-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0003_cronogramavacaciones_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramavacaciones',
            name='fecha_solicitud',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha solicitud'),
        ),
        migrations.AlterField(
            model_name='historicalcronogramavacaciones',
            name='fecha_solicitud',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha solicitud'),
        ),
    ]
