# Generated by Django 4.2.2 on 2023-09-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0004_alter_cronogramavacaciones_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronogramavacaciones',
            options={'ordering': ['-id'], 'verbose_name': 'cronograma vacaciones', 'verbose_name_plural': 'cronogramas vacaciones'},
        ),
    ]
