# Generated by Django 4.2.7 on 2024-01-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0006_archivocronograma_historicalarchivocronograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramavacaciones',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha solicitud'),
        ),
        migrations.AlterField(
            model_name='historicalcronogramavacaciones',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha solicitud'),
        ),
    ]
