# Generated by Django 4.2.2 on 2023-06-29 22:29

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoTrabajadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de eliminación')),
                ('doc', models.FileField(upload_to='./static/archivoTrabajadores')),
            ],
            options={
                'verbose_name': 'Archivo Trabajadores',
                'verbose_name_plural': 'Archivos Trabajadores',
                'db_table': 'Archivo_trabajadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalArchivoTrabajadores',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('doc', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Archivo Trabajadores',
                'verbose_name_plural': 'historical Archivos Trabajadores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTrabajador',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('numero_identificacion', models.CharField(blank=True, max_length=255, verbose_name='Cédula')),
                ('nombres', models.CharField(blank=True, max_length=255, verbose_name='Nombres')),
                ('celular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular')),
                ('correo_personal', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico personal')),
                ('correo_institucional', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo institucional')),
                ('partida_individual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Partida individual')),
                ('rmu_puesto', models.CharField(blank=True, max_length=255, null=True, verbose_name='RMU del puesto')),
                ('estado_servidor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado servidor')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('CÉDULA', 'CÉDULA'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], max_length=255, null=True, verbose_name='Tipo identificación')),
                ('etnia', models.CharField(blank=True, choices=[('Blanco', 'BLANCO'), ('Indigena', 'INDIGENA'), ('Mestizo', 'MESTIZO'), ('Montubio', 'MONTUBIO'), ('Mulato', 'MULATO'), ('Negro', 'NEGRO'), ('Saraguro', 'SRAGURO'), ('Otro', 'OTRO')], max_length=255, null=True, verbose_name='Etnia')),
                ('discapacidad', models.CharField(blank=True, choices=[('Ninguna', 'NINGUNA'), ('Discapacidad', 'DISCAPACIDAD'), ('Sustituto', 'SUSTITUTO')], max_length=255, null=True, verbose_name='Discapacidad')),
                ('estado_maternidad', models.CharField(blank=True, choices=[('Embarazo', 'EMBARAZO'), ('Lactancia', 'LACTANCIA'), ('Ninguno', 'NINGUNO')], max_length=255, null=True, verbose_name='Estado Maternidad')),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'MASCULINO'), ('Femenino', 'FEMENINO')], max_length=255, null=True, verbose_name='Género')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical trabajador',
                'verbose_name_plural': 'historical trabajadores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de eliminación')),
                ('numero_identificacion', models.CharField(blank=True, max_length=255, verbose_name='Cédula')),
                ('nombres', models.CharField(blank=True, max_length=255, verbose_name='Nombres')),
                ('celular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular')),
                ('correo_personal', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico personal')),
                ('correo_institucional', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo institucional')),
                ('partida_individual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Partida individual')),
                ('rmu_puesto', models.CharField(blank=True, max_length=255, null=True, verbose_name='RMU del puesto')),
                ('estado_servidor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado servidor')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('CÉDULA', 'CÉDULA'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], max_length=255, null=True, verbose_name='Tipo identificación')),
                ('etnia', models.CharField(blank=True, choices=[('Blanco', 'BLANCO'), ('Indigena', 'INDIGENA'), ('Mestizo', 'MESTIZO'), ('Montubio', 'MONTUBIO'), ('Mulato', 'MULATO'), ('Negro', 'NEGRO'), ('Saraguro', 'SRAGURO'), ('Otro', 'OTRO')], max_length=255, null=True, verbose_name='Etnia')),
                ('discapacidad', models.CharField(blank=True, choices=[('Ninguna', 'NINGUNA'), ('Discapacidad', 'DISCAPACIDAD'), ('Sustituto', 'SUSTITUTO')], max_length=255, null=True, verbose_name='Discapacidad')),
                ('estado_maternidad', models.CharField(blank=True, choices=[('Embarazo', 'EMBARAZO'), ('Lactancia', 'LACTANCIA'), ('Ninguno', 'NINGUNO')], max_length=255, null=True, verbose_name='Estado Maternidad')),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'MASCULINO'), ('Femenino', 'FEMENINO')], max_length=255, null=True, verbose_name='Género')),
                ('id_denominacion_puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributivo.denominacion_puesto', verbose_name='Denominación del puesto')),
                ('id_modalidad_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributivo.modalidad_laboral', verbose_name='Modalidad laboral')),
                ('id_nivel_ocupacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributivo.nivel_ocupacional', verbose_name='Nivel ocupacional')),
                ('id_regimen_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributivo.regimen_laboral', verbose_name='Regimen laboral')),
                ('id_unidad_organica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributivo.unidad_organica', verbose_name='Unidad orgánica')),
            ],
            options={
                'verbose_name': 'trabajador',
                'verbose_name_plural': 'trabajadores',
                'db_table': 'Trabajador',
                'ordering': ['id'],
            },
        ),
    ]
