# Generated by Django 4.2.2 on 2023-06-29 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributivo', '0002_initial'),
        ('trabajadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrabajador',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltrabajador',
            name='id_denominacion_puesto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='distributivo.denominacion_puesto', verbose_name='Denominación del puesto'),
        ),
        migrations.AddField(
            model_name='historicaltrabajador',
            name='id_modalidad_laboral',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='distributivo.modalidad_laboral', verbose_name='Modalidad laboral'),
        ),
        migrations.AddField(
            model_name='historicaltrabajador',
            name='id_nivel_ocupacional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='distributivo.nivel_ocupacional', verbose_name='Nivel ocupacional'),
        ),
        migrations.AddField(
            model_name='historicaltrabajador',
            name='id_regimen_laboral',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='distributivo.regimen_laboral', verbose_name='Regimen laboral'),
        ),
        migrations.AddField(
            model_name='historicaltrabajador',
            name='id_unidad_organica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='distributivo.unidad_organica', verbose_name='Unidad orgánica'),
        ),
        migrations.AddField(
            model_name='historicalarchivotrabajadores',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
