# Generated by Django 4.2.2 on 2023-07-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_historicaltrabajador_dias_vacaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrabajador',
            name='dias_vacaciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Dias de vacaciones acumulados'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='dias_vacaciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Dias de vacaciones acumulados'),
        ),
    ]
