# Generated by Django 4.2.2 on 2023-07-19 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributivo', '0004_estructura_programatica_and_more'),
        ('trabajadores', '0004_alter_historicaltrabajador_dias_vacaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrabajador',
            name='id_estructura_programatica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='distributivo.estructura_programatica', verbose_name='Estructura programática'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='id_estructura_programatica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributivo.estructura_programatica', verbose_name='Estructura programática'),
        ),
    ]
