# Generated by Django 4.2.2 on 2023-08-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0005_historicaltrabajador_id_estructura_programatica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrabajador',
            name='direccion_domicilio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccioón domicilio'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='direccion_domicilio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccioón domicilio'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajador',
            name='etnia',
            field=models.CharField(blank=True, choices=[('Blanco', 'BLANCO'), ('Indigena', 'INDIGENA'), ('Mestizo', 'MESTIZO'), ('Montubio', 'MONTUBIO'), ('Mulato', 'MULATO'), ('Negro', 'NEGRO'), ('Saraguro', 'SARAGURO'), ('Otro', 'OTRO')], max_length=255, null=True, verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='etnia',
            field=models.CharField(blank=True, choices=[('Blanco', 'BLANCO'), ('Indigena', 'INDIGENA'), ('Mestizo', 'MESTIZO'), ('Montubio', 'MONTUBIO'), ('Mulato', 'MULATO'), ('Negro', 'NEGRO'), ('Saraguro', 'SARAGURO'), ('Otro', 'OTRO')], max_length=255, null=True, verbose_name='Etnia'),
        ),
    ]
