# Generated by Django 4.2.2 on 2023-09-04 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajadores', '0006_historicaltrabajador_direccion_domicilio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonalesTrabajadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de eliminación')),
                ('numHijos', models.IntegerField(blank=True, null=True, verbose_name='Numero de hijos')),
            ],
            options={
                'verbose_name': 'Dato personal trabajador',
                'verbose_name_plural': 'Datos personales trabajadores',
                'db_table': 'Datos_personales_trabajador',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['nombres'], 'verbose_name': 'trabajador', 'verbose_name_plural': 'trabajadores'},
        ),
        migrations.CreateModel(
            name='HistoricalDatosPersonalesTrabajadores',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('numHijos', models.IntegerField(blank=True, null=True, verbose_name='Numero de hijos')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dato personal trabajador',
                'verbose_name_plural': 'historical Datos personales trabajadores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
