# Generated by Django 4.2.2 on 2023-11-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0008_remove_historicaltrabajador_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonalestrabajadores',
            name='numHijos',
        ),
        migrations.RemoveField(
            model_name='historicaldatospersonalestrabajadores',
            name='numHijos',
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='apellido_materno'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='apellido_paterno'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo institucional'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='correo_personal',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico personal'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='detalle_enfermedad',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Detalle enfermedad'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='discapacidad',
            field=models.BooleanField(default=False, verbose_name='Discapacidad'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='enfermedad_catastrofica',
            field=models.BooleanField(default=False, verbose_name='Enfermedad catastrofica'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='etnia',
            field=models.CharField(blank=True, choices=[('Afroecuatoriano', 'AFROECUATORIANO'), ('Blanco', 'BLANCO'), ('Indigena', 'INDIGENA'), ('Mestizo', 'MESTIZO'), ('Montubio', 'MONTUBIO'), ('Mulato', 'MULATO'), ('Negro', 'NEGRO'), ('Saraguro', 'SARAGURO'), ('Otro', 'OTRO')], max_length=255, null=True, verbose_name='Etnia'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'MASCULINO'), ('Femenino', 'FEMENINO'), ('LGBTI', 'LGBTI')], max_length=255, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nacionalidad'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='nacionalidad_indigena',
            field=models.CharField(blank=True, choices=[('Achuar', 'ACHUAR'), ('Al Cofan', 'AL COFAN'), ('Andoa', 'ANDOA'), ('Awa', 'AWA'), ('Cachi', 'CHACHI'), ('Chibuelo', 'CHIBULEO'), ('Epera', 'EPERA'), ('Huancavilca', 'HUANCAVILCA'), ('Huaorani', 'HUAORANI'), ('Kañari', 'KAÑARI'), ('Karanki', 'KARANKI'), ('Kayambi', 'KAYAMBI'), ('Kichwa', 'KICHWA'), ('Kitukara', 'KITUKARA'), ('Manta', 'MANTA'), ('Natabuela', 'NATABUELA'), ('Otavalo', 'OTAVALO'), ('Paltas', 'PALTAS'), ('Panzaleo', 'PANZALEO'), ('Pastos', 'PASTOS'), ('Salasaka', 'SALASAKA'), ('Saraguro', 'SARAGURO'), ('Secoya', 'SECOYA'), ('Shuar', 'SHUAR'), ('Siona', 'SIONA'), ('Tsachila', 'TSACHILA'), ('Waorani', 'WAORANI'), ('Zapara', 'ZAPARA'), ('Otro', 'OTRO')], max_length=255, null=True, verbose_name='Nacionalidad indigena'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='nombre_enfermedad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de enfermedad catastrofica'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='num_carnet_conadis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número del carnet de conadis'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='num_libreta_militar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de libreta militar'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='num_pasaporte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='número de pasaporte'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='porcentaje_discapacidad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Porcentaje discapacidad'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='primer_nombre'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='provincia'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo_nombre'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='tipo_discapacidad',
            field=models.CharField(blank=True, choices=[('Física Motora', 'FISICA MOTORA'), ('Auditiva', 'AUDITIVA'), ('Intelectual', 'INTELECTUAL'), ('Lenguaje', 'LENGUAJE'), ('Psicosocial', 'PSICOSOCIAL'), ('Visual', 'VISUAL')], max_length=255, null=True, verbose_name='Tipo de discapacidad'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='tipo_libreta',
            field=models.CharField(blank=True, choices=[('Reservista', 'RESERVISTA'), ('No Favorecido', 'NO FAVORECIDO'), ('Extento', 'EXTENTO'), ('Extrangero', 'EXTRANGERO'), ('No Idoneo', 'MO IDONEO'), ('Remiso Sancionado', 'REMISO SAMCIONADO'), ('Licencia Final', 'LICENCIA FINAL')], max_length=255, null=True, verbose_name='Tipo de libreta militar'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='tipo_pasaporte',
            field=models.CharField(blank=True, choices=[('pasaporte', 'PASAPORTE'), ('visa', 'VISA'), ('carnet de refugiado', 'CARNET DE REFUGIADO')], max_length=255, null=True, verbose_name='Pasaporte'),
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('O Positivo', 'O POSITIVO'), ('O Negativo', 'O NEGATIVO'), ('A Positivo', 'A POSITIVO'), ('A Negativo', 'A NEGATIVO'), ('B Positivo', 'B POSITIVO'), ('B Negativo', 'B NEGATIVO'), ('AB Positivo', 'AB POSITIVO'), ('AB Negativo', 'AB NEGATIVO')], max_length=255, null=True, verbose_name='Tipo de sangre'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='apellido_materno'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='apellido_paterno'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo institucional'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='correo_personal',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico personal'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='detalle_enfermedad',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Detalle enfermedad'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='discapacidad',
            field=models.BooleanField(default=False, verbose_name='Discapacidad'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='enfermedad_catastrofica',
            field=models.BooleanField(default=False, verbose_name='Enfermedad catastrofica'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='etnia',
            field=models.CharField(blank=True, choices=[('Afroecuatoriano', 'AFROECUATORIANO'), ('Blanco', 'BLANCO'), ('Indigena', 'INDIGENA'), ('Mestizo', 'MESTIZO'), ('Montubio', 'MONTUBIO'), ('Mulato', 'MULATO'), ('Negro', 'NEGRO'), ('Saraguro', 'SARAGURO'), ('Otro', 'OTRO')], max_length=255, null=True, verbose_name='Etnia'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'MASCULINO'), ('Femenino', 'FEMENINO'), ('LGBTI', 'LGBTI')], max_length=255, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nacionalidad'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='nacionalidad_indigena',
            field=models.CharField(blank=True, choices=[('Achuar', 'ACHUAR'), ('Al Cofan', 'AL COFAN'), ('Andoa', 'ANDOA'), ('Awa', 'AWA'), ('Cachi', 'CHACHI'), ('Chibuelo', 'CHIBULEO'), ('Epera', 'EPERA'), ('Huancavilca', 'HUANCAVILCA'), ('Huaorani', 'HUAORANI'), ('Kañari', 'KAÑARI'), ('Karanki', 'KARANKI'), ('Kayambi', 'KAYAMBI'), ('Kichwa', 'KICHWA'), ('Kitukara', 'KITUKARA'), ('Manta', 'MANTA'), ('Natabuela', 'NATABUELA'), ('Otavalo', 'OTAVALO'), ('Paltas', 'PALTAS'), ('Panzaleo', 'PANZALEO'), ('Pastos', 'PASTOS'), ('Salasaka', 'SALASAKA'), ('Saraguro', 'SARAGURO'), ('Secoya', 'SECOYA'), ('Shuar', 'SHUAR'), ('Siona', 'SIONA'), ('Tsachila', 'TSACHILA'), ('Waorani', 'WAORANI'), ('Zapara', 'ZAPARA'), ('Otro', 'OTRO')], max_length=255, null=True, verbose_name='Nacionalidad indigena'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='nombre_enfermedad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de enfermedad catastrofica'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='num_carnet_conadis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número del carnet de conadis'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='num_libreta_militar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de libreta militar'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='num_pasaporte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='número de pasaporte'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='porcentaje_discapacidad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Porcentaje discapacidad'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='primer_nombre'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='provincia'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo_nombre'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='tipo_discapacidad',
            field=models.CharField(blank=True, choices=[('Física Motora', 'FISICA MOTORA'), ('Auditiva', 'AUDITIVA'), ('Intelectual', 'INTELECTUAL'), ('Lenguaje', 'LENGUAJE'), ('Psicosocial', 'PSICOSOCIAL'), ('Visual', 'VISUAL')], max_length=255, null=True, verbose_name='Tipo de discapacidad'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='tipo_libreta',
            field=models.CharField(blank=True, choices=[('Reservista', 'RESERVISTA'), ('No Favorecido', 'NO FAVORECIDO'), ('Extento', 'EXTENTO'), ('Extrangero', 'EXTRANGERO'), ('No Idoneo', 'MO IDONEO'), ('Remiso Sancionado', 'REMISO SAMCIONADO'), ('Licencia Final', 'LICENCIA FINAL')], max_length=255, null=True, verbose_name='Tipo de libreta militar'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='tipo_pasaporte',
            field=models.CharField(blank=True, choices=[('pasaporte', 'PASAPORTE'), ('visa', 'VISA'), ('carnet de refugiado', 'CARNET DE REFUGIADO')], max_length=255, null=True, verbose_name='Pasaporte'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('O Positivo', 'O POSITIVO'), ('O Negativo', 'O NEGATIVO'), ('A Positivo', 'A POSITIVO'), ('A Negativo', 'A NEGATIVO'), ('B Positivo', 'B POSITIVO'), ('B Negativo', 'B NEGATIVO'), ('AB Positivo', 'AB POSITIVO'), ('AB Negativo', 'AB NEGATIVO')], max_length=255, null=True, verbose_name='Tipo de sangre'),
        ),
    ]
