# Generated by Django 4.2.2 on 2023-11-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0009_remove_datospersonalestrabajadores_numhijos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonalestrabajadores',
            name='nombre_enfermedad',
        ),
        migrations.RemoveField(
            model_name='historicaldatospersonalestrabajadores',
            name='nombre_enfermedad',
        ),
        migrations.AddField(
            model_name='datospersonalestrabajadores',
            name='tipo_enfermedad',
            field=models.CharField(blank=True, choices=[('Aneurisma tóraco-abdominaI', 'ANEURISNA TORACO-ABDOMINAL'), ('Insuficiencia renal crónica', 'INSUFICIENCIA RENAL CRONICA'), ('Malformaciones arterio venosas cerebrales', 'MALFORMACIONES ARTERIO VENOSAS CEREBRALES'), ('Malformaciones congénitas ', 'MALFORMACIONES CONGENITAS'), ('Secuelas de quemaduras graves', 'SECUELAS DE QUEMADURAS GRAVES'), ('Síndrome de Klippel Trenaunay', 'SINDROME DE KLIPPERL TRENAUNAY'), ('Todo tipo de cáncer', 'TODO TIPOS DE CANCER'), ('Trasplante de órganos: riñón, hígado, médula ósea', 'TRANSPLANTE DE ORGANOS: RIÑON, HIGADO, MEDULA OSEA'), ('Tumor cerebral en cualquier estado y de cualquier tipo', 'TUMOR CEREBRAL EN CUALQUIER ESTADO Y TIPO'), ('Tumores malignos', 'TUMORES MALIGNOS'), ('Enfermedad de Hodgkin', 'ENFERMEDAD DE HODGKIN'), ('Leucemia', 'LEUCEMIA'), ('Carcinoma', 'CARCINOMA'), ('Otras enfermedades', 'OTRAS ENFERMEDADES')], max_length=255, null=True, verbose_name='Tipo de sangre'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonalestrabajadores',
            name='tipo_enfermedad',
            field=models.CharField(blank=True, choices=[('Aneurisma tóraco-abdominaI', 'ANEURISNA TORACO-ABDOMINAL'), ('Insuficiencia renal crónica', 'INSUFICIENCIA RENAL CRONICA'), ('Malformaciones arterio venosas cerebrales', 'MALFORMACIONES ARTERIO VENOSAS CEREBRALES'), ('Malformaciones congénitas ', 'MALFORMACIONES CONGENITAS'), ('Secuelas de quemaduras graves', 'SECUELAS DE QUEMADURAS GRAVES'), ('Síndrome de Klippel Trenaunay', 'SINDROME DE KLIPPERL TRENAUNAY'), ('Todo tipo de cáncer', 'TODO TIPOS DE CANCER'), ('Trasplante de órganos: riñón, hígado, médula ósea', 'TRANSPLANTE DE ORGANOS: RIÑON, HIGADO, MEDULA OSEA'), ('Tumor cerebral en cualquier estado y de cualquier tipo', 'TUMOR CEREBRAL EN CUALQUIER ESTADO Y TIPO'), ('Tumores malignos', 'TUMORES MALIGNOS'), ('Enfermedad de Hodgkin', 'ENFERMEDAD DE HODGKIN'), ('Leucemia', 'LEUCEMIA'), ('Carcinoma', 'CARCINOMA'), ('Otras enfermedades', 'OTRAS ENFERMEDADES')], max_length=255, null=True, verbose_name='Tipo de sangre'),
        ),
    ]
