# Generated by Django 4.2.2 on 2023-11-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0011_informacionbancaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinformacionbancaria',
            old_name='institucion_bancaria',
            new_name='institucion_financiera',
        ),
        migrations.RenameField(
            model_name='informacionbancaria',
            old_name='institucion_bancaria',
            new_name='institucion_financiera',
        ),
    ]
