# Generated by Django 4.2.7 on 2023-12-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0013_correotrabajadores_vacacionestrabajadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivotrabajadores',
            name='doc',
            field=models.FileField(upload_to='archivoTrabajadores'),
        ),
        migrations.AlterField(
            model_name='correotrabajadores',
            name='doc',
            field=models.FileField(upload_to='correosTrabajadores'),
        ),
        migrations.AlterField(
            model_name='vacacionestrabajadores',
            name='doc',
            field=models.FileField(upload_to='vacacionesTrabajadores'),
        ),
    ]
