# Generated by Django 4.2.7 on 2024-11-29 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributivo', '0011_alter_escala_ocupacional_options_and_more'),
        ('trabajadores', '0014_alter_archivotrabajadores_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrabajador',
            name='id_escala_ocupacional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='distributivo.escala_ocupacional', verbose_name='Escala ocupacional'),
        ),
        migrations.AddField(
            model_name='historicaltrabajador',
            name='id_grado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='distributivo.grado', verbose_name='Grado'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='id_escala_ocupacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributivo.escala_ocupacional', verbose_name='Escala ocupacional'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='id_grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributivo.grado', verbose_name='Grado'),
        ),
    ]
