# Generated by Django 4.2.7 on 2024-12-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0015_historicaltrabajador_id_escala_ocupacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrabajador',
            name='dias_vacaciones',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Dias de vacaciones acumulados'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='dias_vacaciones',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Dias de vacaciones acumulados'),
        ),
    ]
