# Generated by Django 4.2.2 on 2023-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='tipoUsuario',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tipo de usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tipo de usuario'),
        ),
    ]
