# Generated by Django 4.2.2 on 2023-09-04 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributivo', '0004_estructura_programatica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de eliminación')),
                ('proceso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'proceso',
                'verbose_name_plural': 'procesos',
                'db_table': 'Proceso',
                'ordering': ['proceso'],
            },
        ),
        migrations.AlterModelOptions(
            name='denominacion_puesto',
            options={'ordering': ['denominacion_puesto'], 'verbose_name': 'denominacion puesto', 'verbose_name_plural': 'denominaciones puestos'},
        ),
        migrations.AlterModelOptions(
            name='estado_puesto',
            options={'ordering': ['estado_puesto'], 'verbose_name': 'estado puesto', 'verbose_name_plural': 'estados puesto'},
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['grado'], 'verbose_name': 'grado', 'verbose_name_plural': 'grados'},
        ),
        migrations.AlterModelOptions(
            name='modalidad_laboral',
            options={'ordering': ['modalidad_laboral'], 'verbose_name': 'modalidad laboral', 'verbose_name_plural': 'modalidades laborales'},
        ),
        migrations.AlterModelOptions(
            name='nivel_ocupacional',
            options={'ordering': ['nivel_ocupacional'], 'verbose_name': 'nivel ocupacional', 'verbose_name_plural': 'nivel ocupacional'},
        ),
        migrations.AlterModelOptions(
            name='regimen_laboral',
            options={'ordering': ['regimen_laboral'], 'verbose_name': 'regimen laboral', 'verbose_name_plural': 'regimen laboral'},
        ),
        migrations.CreateModel(
            name='HistoricalProceso',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('proceso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proceso')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proceso',
                'verbose_name_plural': 'historical procesos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
