# Generated by Django 4.2.2 on 2023-10-13 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributivo', '0008_alter_denominacion_puesto_cod_denominacion_puesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denominacion_puesto',
            name='id_proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributivo.proceso', verbose_name='Proceso'),
        ),
        migrations.AddField(
            model_name='historicaldenominacion_puesto',
            name='id_proceso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='distributivo.proceso', verbose_name='Proceso'),
        ),
    ]
