# Generated by Django 4.2.7 on 2024-11-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributivo', '0010_escala_ocupacional_historicalescala_ocupacional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala_ocupacional',
            options={'ordering': ['escala_ocupacional'], 'verbose_name': 'escala ocupacional', 'verbose_name_plural': 'escalas ocupacionales'},
        ),
        migrations.AlterModelOptions(
            name='historicalescala_ocupacional',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical escala ocupacional', 'verbose_name_plural': 'historical escalas ocupacionales'},
        ),
    ]
