# Generated by Django 4.2.7 on 2024-12-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributivo', '0011_alter_escala_ocupacional_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['id'], 'verbose_name': 'grado', 'verbose_name_plural': 'grados'},
        ),
    ]
