# Generated by Django 4.2.2 on 2023-08-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='hora',
            field=models.DateField(blank=True, null=True, verbose_name='Hora registro asistencia'),
        ),
        migrations.AddField(
            model_name='historicalasistencia',
            name='hora',
            field=models.DateField(blank=True, null=True, verbose_name='Hora registro asistencia'),
        ),
    ]
