# Generated by Django 4.2.2 on 2023-08-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_asistencia_hora_historicalasistencia_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro asistencia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora registro asistencia'),
        ),
        migrations.AlterField(
            model_name='historicalasistencia',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro asistencia'),
        ),
        migrations.AlterField(
            model_name='historicalasistencia',
            name='hora',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora registro asistencia'),
        ),
    ]
