# Generated by Django 4.2.2 on 2023-09-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_alter_asistencia_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-id'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
    ]
